services:
  app:
    build:
      dockerfile: src/Dockerfile
      context: .
    restart: always
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo-server
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db

#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo-server
#      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
#      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
#    depends_on:
#      - mongodb

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    depends_on:
      - app
    ports:
      - 80:80


  logstash:
    image: logstash:8.13.0
    environment:
      ES_HOST: "elasticsearch:9200"
    expose:
      - 5044/udp
      - 5045
#    ports:
#      - "5044:5044/udp"
#      - "5045:5045"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    depends_on:
      - app
      - nginx

  elasticsearch:
    image: elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - 9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    depends_on:
      - logstash

  kibana:
    image: kibana:8.13.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  filebeat:
    image: elastic/filebeat:8.13.0
    entrypoint: "filebeat -e -strict.perms=false"
    user: root
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - app
      - nginx
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash

volumes:
  mongodb_data_container:
  esdata:
