services:
  app:
    build:
      dockerfile: src/Dockerfile
      context: .
    restart: always
    env_file:
      - ./.env
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - app_log_data:/opt/logs
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo-server
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  app_log_data:

