services:
  mongodb:
    image: mongo
    container_name: mongo_db_research
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db


  postgres_db:
    image: postgres:15.0-alpine
    container_name: postgres_db_research
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_research:/var/lib/postgresql/data/
    env_file:
      - ../.env

volumes:
  mongodb_data_container:
  postgres_data_research:
